# RDKV HAL component versions

# RDKV HAL component versions of raspberrypi4
SRCREV_pn-devicesettings-hal-raspberrypi4 = "1.0.2"
PV_pn-devicesettings-hal-raspberrypi4 = "2.0.0"
PR_pn-devicesettings-hal-raspberrypi4 = "r0"
PACKAGE_ARCH_pn-${MLPREFIX}devicesettings-hal-raspberrypi4 = "${VENDOR_LAYER_EXTENSION}"

SRCREV_pn-iarmmgrs-hal-raspberrypi4 = "1.0.1"
PV_pn-iarmmgrs-hal-raspberrypi4 = "2.0.1"
PR_pn-iarmmgrs-hal-raspberrypi4 = "r0"
PACKAGE_ARCH_pn-${MLPREFIX}iarmmgrs-hal-raspberrypi4 = "${VENDOR_LAYER_EXTENSION}"

SRCREV_pn-mfrlibs-hal-raspberrypi4 = "1.0.1"
PV_pn-mfrlibs-hal-raspberrypi4 = "1.0.0"
PR_pn-mfrlibs-hal-raspberrypi4 = "r0"
PACKAGE_ARCH_pn-${MLPREFIX}mfrlibs-hal-raspberrypi4 = "${VENDOR_LAYER_EXTENSION}"

SRCREV_pn-hdmicec-hal-raspberrypi4 = "1.0.0"
PV_pn-hdmicec-hal-raspberrypi4 = "1.0.0"
PR_pn-hdmicec-hal-raspberrypi4 = "r0"
PACKAGE_ARCH_pn-${MLPREFIX}hdmicec-hal-raspberrypi4 = "${VENDOR_LAYER_EXTENSION}"
