# RDKV HAL component versions

# RDKV HAL component versions of raspberrypi4
SRCREV:pn-devicesettings-hal-raspberrypi4 = "7419888aaa9a3125980f81a324f6ad4fb83caa7b"
PV:pn-devicesettings-hal-raspberrypi4 = "2.0.0"
PR:pn-devicesettings-hal-raspberrypi4 = "r0"
PACKAGE_ARCH:pn-devicesettings-hal-raspberrypi4 = "${VENDOR_LAYER_EXTENSION}"

SRCREV:pn-iarmmgrs-hal-raspberrypi4 = "f7c7d360fd856e06b65097333e77a0c1c5d313ea"
PV:pn-iarmmgrs-hal-raspberrypi4 = "2.0.1"
PR:pn-iarmmgrs-hal-raspberrypi4 = "r0"
PACKAGE_ARCH:pn-iarmmgrs-hal-raspberrypi4 = "${VENDOR_LAYER_EXTENSION}"

SRCREV:pn-pwrmgr-hal-raspberrypi4 = "4781328b379ce4d88084ec75ca714733212fad40"
PV:pn-pwrmgr-hal-raspberrypi4 = "1.0.0"
PR:pn-pwrmgr-hal-raspberrypi4 = "r0"
PACKAGE_ARCH:pn-pwrmgr-hal-raspberrypi4 = "${VENDOR_LAYER_EXTENSION}"

SRCREV:pn-deepsleepmgr-hal-raspberrypi4 = "5299b42a8bf4c462303e77caf2d0441057929e62"
PV:pn-deepsleepmgr-hal-raspberrypi4 = "1.0.0"
PR:pn-deepsleepmgr-hal-raspberrypi4 = "r0"
PACKAGE_ARCH:pn-deepsleepmgr-hal-raspberrypi4 = "${VENDOR_LAYER_EXTENSION}"

SRCREV:pn-pwrmgr-hal-raspberrypi4 = "1.1.0"
PV:pn-pwrmgr-hal-raspberrypi4 = "1.0.0"
PR:pn-pwrmgr-hal-raspberrypi4 = "r0"
PACKAGE_ARCH:pn-pwrmgr-hal-raspberrypi4 = "${VENDOR_LAYER_EXTENSION}"

SRCREV:pn-deepsleepmgr-hal-raspberrypi4 = "1.1.0"
PV:pn-deepsleepmgr-hal-raspberrypi4 = "1.0.0"
PR:pn-deepsleepmgr-hal-raspberrypi4 = "r0"
PACKAGE_ARCH:pn-deepsleepmgr-hal-raspberrypi4 = "${VENDOR_LAYER_EXTENSION}"

SRCREV:pn-mfrlibs-hal-raspberrypi4 = "43b84464afdede3cb2c0a108ec6ad14107cc8c5b"
PV:pn-mfrlibs-hal-raspberrypi4 = "1.0.0"
PR:pn-mfrlibs-hal-raspberrypi4 = "r0"
PACKAGE_ARCH:pn-mfrlibs-hal-raspberrypi4 = "${VENDOR_LAYER_EXTENSION}"

SRCREV:pn-hdmicec-hal-raspberrypi4 = "81610f5daf4f2167a30ad9aae8e18c2846e51530"
PV:pn-hdmicec-hal-raspberrypi4 = "1.0.0"
PR:pn-hdmicec-hal-raspberrypi4 = "r0"
PACKAGE_ARCH:pn-hdmicec-hal-raspberrypi4 = "${VENDOR_LAYER_EXTENSION}"

SRCREV:pn-systemaudioplatform = "59662783df1c0c7d04016c6f90da27516c070109"
PV:pn-systemaudioplatform = "1.0.0"
PR:pn-systemaudioplatform = "r0"
PACKAGE_ARCH:pn-systemaudioplatform = "${VENDOR_LAYER_EXTENSION}"
